### ISSUE TITLE
Publish 0.3.1 version

### ISSUE THREAD

**Issue by skateonrails** [wilmoore/node-supertest-koa-agent#6]
Hey @wilmoore, could you please publish this 0.3.1 version to npm? 😄

**Comment by wilmoore** [comment]
Published 0.3.2 after your `readme.md` update. Thank you!

**Comment by wilmoore** [comment]
@skateonrails 

I've invited you as a collaborator in case you'd be happy to continue maintaining. You've contributed to this repo more than me as of late.

**Comment by skateonrails** [comment]
@wilmoore Thank you very much!

**Comment by wilmoore** [comment]
You're welcome, and thank you as well!
