### ISSUE TITLE
deprecated warning

### ISSUE THREAD

**Issue by ctfrancia** [wilmoore/node-supertest-koa-agent#8]
not sure if this is still actively maintained or not but getting some deprecation warnings and thought that an update of supertest would be good

>npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated superagent@3.8.3: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.

**Comment by skateonrails** [comment]
Hi @ctfrancia,

I did an upgrade of the current packages, including the `supertest` package. But it seems that the latest `supertest` still uses the 3.8.3 `superagent` lib...
Anyway, I hope this PR helps with your warnings.

**Comment by ctfrancia** [comment]
Hi I hope that it does as well. I forgot to come back here and comment how the warning says that when the next version comes out the warning will be removed. I was just going crazy because my package.json says that I was using the newest version so I was going crazy looking for where I may have had that specific version installed

**Comment by wilmoore** [comment]
Merged...thanks @skateonrails and @ctfrancia
